Fix the build of the image including the FT sensor dependencies.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,15 +1,38 @@
+stages:
+  - base
+  - derived
+  - cleanup
+
+# Factorized script for defining image variables
+.define-image-variables:
+  script:
+    - DATE="pr-build"
+    - |
+      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
+        # Use the source branch of the merge request
+        export BRANCH_NAME=$(echo ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} | tr "/" -)
+      else
+        # Use the current branch for pushes
+        export BRANCH_NAME=$(echo ${CI_COMMIT_BRANCH} | tr "/" -)
+        DATE=$(date -d "${CI_PIPELINE_CREATED_AT:0:10}" +"%d-%m-%Y")
+      fi
+    - BASE_IMAGE="${CI_REGISTRY_IMAGE}:${BRANCH_NAME}-base-${DATE}"
+    - IMAGE_NAME_SHORT="${CI_REGISTRY_IMAGE}:${BRANCH_NAME}-${IMAGE_NAME}"
+    - IMAGE_NAME_LONG="$IMAGE_NAME_SHORT-${DATE}"
+    - echo "Building Docker image with the following parameters:"
+    - echo "BRANCH_NAME = ${BRANCH_NAME}"
+    - echo "BASE_IMAGE = ${BASE_IMAGE}"
+    - echo "IMAGE_NAME_SHORT = ${IMAGE_NAME_SHORT}"
+    - echo "IMAGE_NAME_LONG = ${IMAGE_NAME_LONG}"
+
 .build-common:
   timeout: 7 hours 0 minutes
   image: docker
   rules:
     - if: '$CI_COMMIT_BRANCH == "humble-devel"'
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
   script:
-    - DATE=$(date -d "${CI_PIPELINE_CREATED_AT:0:10}" +"%d-%m-%Y")
-    # For true base image this will be ignored as a build argument
-    - export BRANCH_NAME=$(echo ${CI_COMMIT_BRANCH} | tr "/" -)
-    - BASE_IMAGE="${CI_REGISTRY_IMAGE}:${BRANCH_NAME}-base-${DATE}"
-    - IMAGE_NAME_SHORT="${CI_REGISTRY_IMAGE}:${BRANCH_NAME}-${IMAGE_NAME}"
-    - IMAGE_NAME_LONG="$IMAGE_NAME_SHORT-${DATE}"
+    - !reference [.define-image-variables, script]
     - docker build
         -t "${IMAGE_NAME_SHORT}"
         -t "${IMAGE_NAME_LONG}"
@@ -20,16 +43,6 @@
     - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
     - docker push "${IMAGE_NAME_SHORT}"
     - docker push "${IMAGE_NAME_LONG}"
-  variables:
-    IMAGE_NAME: base
-    DOCKER_FILE: ./.devcontainer/Dockerfile.base
-    CONTEXT_PATH: ./.devcontainer
-    HAPPYPOSE_INSTALL_TYPE: cpu
-
-stages:
-  - base
-  - derived
-
 
 build-base-image:
   stage: base
@@ -77,3 +90,50 @@ build-realtime-control-image:
     IMAGE_NAME: realtime-control
     DOCKER_FILE: ./.devcontainer/Dockerfile.realtime
     CONTEXT_PATH: ./.devcontainer
+
+# Common cleanup logic for a single image
+.cleanup-common:
+  stage: cleanup
+  image: docker
+  script:
+    - !reference [.define-image-variables, script]
+    - echo "Cleaning up Docker images for branch= $BRANCH_NAME"
+    - echo "Removing images= $IMAGE_NAME_SHORT, $IMAGE_NAME_LONG, $BASE_IMAGE"
+    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
+    - docker rmi "${IMAGE_NAME_SHORT}" || true
+    - docker rmi "${IMAGE_NAME_LONG}" || true
+    - docker rmi "${BASE_IMAGE}" || true
+  rules:
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+      when: always
+  allow_failure: true
+
+# Cleanup job for the base image
+cleanup-base-image:
+  extends: .cleanup-common
+  variables:
+    IMAGE_NAME: base
+
+# Cleanup job for the control image
+cleanup-control-image:
+  extends: .cleanup-common
+  variables:
+    IMAGE_NAME: control
+
+# Cleanup job for the CPU vision image
+cleanup-cpu-vision-image:
+  extends: .cleanup-common
+  variables:
+    IMAGE_NAME: vision
+
+# Cleanup job for the CUDA vision image
+cleanup-cuda-vision-image:
+  extends: .cleanup-common
+  variables:
+    IMAGE_NAME: vision-cuda
+
+# Cleanup job for the realtime control image
+cleanup-realtime-control-image:
+  extends: .cleanup-common
+  variables:
+    IMAGE_NAME: realtime-control
