[CI] Attmept to fix: This GitLab CI configuration is invalid: jobs:cleanup-docker-images:script config should be a string or a nested array of strings up to 10 levels deep. .

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -44,34 +44,6 @@ stages:
     - docker push "${IMAGE_NAME_SHORT}"
     - docker push "${IMAGE_NAME_LONG}"
 
-cleanup-docker-images:
-  stage: cleanup
-  image: docker
-  script:
-    - DATE="pr-build"
-    - if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
-        export BRANCH_NAME=$(echo ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} | tr "/" -);
-      else
-        export BRANCH_NAME=$(echo ${CI_COMMIT_BRANCH} | tr "/" -);
-        DATE=$(date -d "${CI_PIPELINE_CREATED_AT:0:10}" +"%d-%m-%Y");
-      fi
-    - echo "Cleaning up Docker images for branch: $BRANCH_NAME"
-    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
-    - |
-      for IMAGE_NAME in base control vision vision-cuda realtime-control; do
-        IMAGE_NAME_SHORT="${CI_REGISTRY_IMAGE}:${BRANCH_NAME}-${IMAGE_NAME}" &&
-        IMAGE_NAME_LONG="${IMAGE_NAME_SHORT}-${DATE}" &&
-        BASE_IMAGE="${CI_REGISTRY_IMAGE}:${BRANCH_NAME}-base-${DATE}" &&
-        echo "Removing images: $IMAGE_NAME_SHORT, $IMAGE_NAME_LONG, $BASE_IMAGE" &&
-        docker rmi "${IMAGE_NAME_SHORT}" || true &&
-        docker rmi "${IMAGE_NAME_LONG}" || true &&
-        docker rmi "${BASE_IMAGE}" || true &&
-      done
-  rules:
-    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
-      when: always
-  allow_failure: true
-
 build-base-image:
   stage: base
   extends: .build-common
@@ -118,3 +90,50 @@ build-realtime-control-image:
     IMAGE_NAME: realtime-control
     DOCKER_FILE: ./.devcontainer/Dockerfile.realtime
     CONTEXT_PATH: ./.devcontainer
+
+# Common cleanup logic for a single image
+.cleanup-common:
+  stage: cleanup
+  image: docker
+  script:
+    - !reference [.define-image-variables, script]
+    - echo "Cleaning up Docker images for branch: $BRANCH_NAME"
+    - echo "Removing images: $IMAGE_NAME_SHORT, $IMAGE_NAME_LONG, $BASE_IMAGE"
+    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
+    - docker rmi "${IMAGE_NAME_SHORT}" || true
+    - docker rmi "${IMAGE_NAME_LONG}" || true
+    - docker rmi "${BASE_IMAGE}" || true
+  rules:
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+      when: always
+  allow_failure: true
+
+# Cleanup job for the base image
+cleanup-base-image:
+  extends: .cleanup-common
+  variables:
+    IMAGE_NAME: base
+
+# Cleanup job for the control image
+cleanup-control-image:
+  extends: .cleanup-common
+  variables:
+    IMAGE_NAME: control
+
+# Cleanup job for the CPU vision image
+cleanup-cpu-vision-image:
+  extends: .cleanup-common
+  variables:
+    IMAGE_NAME: vision
+
+# Cleanup job for the CUDA vision image
+cleanup-cuda-vision-image:
+  extends: .cleanup-common
+  variables:
+    IMAGE_NAME: vision-cuda
+
+# Cleanup job for the realtime control image
+cleanup-realtime-control-image:
+  extends: .cleanup-common
+  variables:
+    IMAGE_NAME: realtime-control
